### PR TITLE
ni_sh_a.char IDE for Python

### PR DESCRIPTION
**Pull request by PIYUSH-MISHRA-00**
#167 
A simple and basic python interpreter to execute python codes

### CODE REVIEW

**Review by PIYUSH-MISHRA-00 — COMMENTED** [review]
@AnanyaDas162 
IDE added and github.sh directory deleted

**Comment by AnanyaDas162** [comment]
Yeah, that's great! But here I can see that you have edited my Readme. So please don't do that.

**Comment by PIYUSH-MISHRA-00** [comment]
> Yeah, that's great! But here I can see that you have edited my Readme. So please don't do that.
Okay but the readme inside the folder is for explanation of the project how to use it

**Comment by PIYUSH-MISHRA-00** [comment]
> Yeah, that's great! But here I can see that you have edited my Readme. So please don't do that.

Updated and the readme.

**Pull request closed without merging**
